main: lowbrain.mcgravity.Main
name: MCGravity
version: 1.2.0
author: Lowbrain, based on DewDD Gravity
description: Make minecraft more realistic with a new approach of real life gravity
commands:
   MCGravity:
      description: Restart MCGravity and reload config file
      usage: /MCGravity reload
      permission: MCGravity.reload
      permission-message: You don't have permission to reload